/* this code was generated by automated tool, 
   should not edit by hand */

export interface NewsService {
  GetAllNews(request: Empty): Promise<NewsList>;
}

export interface News {
  id?: string;
  title?: string;
  body?: string;
  postImage?: string;
}

export interface NewsList {
  news?: News[];
}

export interface Empty {

}
